Repository chachacreate/chachacreate_fe, pull requests merged in 2025-09, with the labels that each got.

#92 ✨ feat: 클래스 예약/결제-완료 API 연결
  package.json
  src/domains/main/areas/home/features/class-order/pages/MainClassOrderPage.tsx
  src/domains/main/areas/home/features/class-order/pages/MainClassOrderResultPage.tsx
Labels: ✨ feat

#96 ✨ feat: loginRoutes 추가
  src/app/App.tsx
  src/domains/common/auth/routes.ts
  src/domains/main/routes.ts
  src/main.tsx
Labels: ♻️ refactor, ✨ feat

#125 🐛 fix: buyerRoutes 동적 경로 충돌 해결
  src/domains/buyer/routes.ts
Labels: 🐛 fix

#126 ✨feat: 판매자 클래스 정산 페이지 api 연결
  src/domains/seller/areas/settlement/features/class/pages/SellerSettlementClass.tsx
Labels: ✨ feat

#146 ✨ feat: 주문/발송 관리 조회 API 연결
  src/domains/seller/areas/product/features/order/pages/ProductOrder.tsx
Labels: ✨ feat

#166 ✨ feat: 상품 상세 페이지 조회 API 연결
  src/domains/main/areas/home/features/products/pages/MainProductsDetail.tsx
  src/domains/main/areas/home/features/products/pages/MainProductsPage.tsx
  src/domains/main/areas/home/features/products/routes.ts
  src/domains/main/routes.ts
Labels: ♻️ refactor, ✨ feat, 🚧 working in progress

#173 🐛 fix: 판매자 메인 페이지 매출그래프 api 연결
  src/domains/seller/areas/main/pages/SellerMain.tsx
Labels: 🐛 fix

#208 ✨ feat: 주문 상세 페이지 취소/환불 API 연결
  src/domains/main/areas/mypage/pages/MainMypageOrderdetail.tsx
Labels: ✨ feat

#215 ✨ feat: 마이페이지 리뷰 조회 api 연결
  src/domains/main/areas/mypage/pages/MainMypageMyreviews.tsx
Labels: ✨ feat

#231 💄 style: 마이정보페이지에서 보이는 디버그 정보 코드 주석처리
  src/domains/main/areas/mypage/pages/MainMypagePage.tsx
Labels: 💄 style

#236 🐛 fix: 전체상품목록 카테고리 조회 수정
  src/domains/main/areas/home/features/products/pages/MainProductsPage.tsx
Labels: 🐛 fix

#240 🐛 fix: 메인 전체상품 정렬조회 오류 수정
  src/domains/main/areas/home/features/products/pages/MainProductsPage.tsx
Labels: 🐛 fix

#242 ✨ feat: 판매자 페이지 클래스 수정 API 연결
  src/domains/seller/areas/class/features/edit/pages/ClassEdit.tsx
  src/domains/seller/areas/class/features/list/pages/ClassList.tsx
Labels: ✨ feat, 🎨 design

#246 🐛 fix: SellerSidenavbar 오류 수정
  src/domains/seller/areas/main/pages/SellerMain.tsx
  src/shared/areas/navigation/features/sidenavbar/seller/SellerSidenavbar.tsx
Labels: 🎨 design, 🐛 fix

#247 🎨 design: 판매자 관리 페이지 테이블 UI 수정
  src/domains/seller/areas/product/features/list/pages/ProductList.tsx
  src/domains/seller/areas/product/features/review/pages/ProductReview.tsx
Labels: 🎨 design

#249 🐛 fix: 판매자 정산메인-주간 정산 금액,일별 합계 조회 수정
  src/domains/seller/areas/settlement/features/main/pages/SellerSettlementMain.tsx
Labels: 🐛 fix

#254 🐛 fix: 스토어 전체상품 페이지 판매/조회수 오류 수정
  src/domains/buyer/areas/products/pages/Storeproducts.tsx
Labels: 🐛 fix

#257 🐛 fix: 상품 수정 페이지 사진 오류 수정
  src/domains/seller/areas/product/features/edit/pages/ProductEdit.tsx
  src/domains/seller/areas/product/features/insert/pages/ProductInsert.tsx
  src/shared/areas/layout/features/header/Header.tsx
  src/shared/areas/navigation/features/sidenavbar/seller/SellerSidenavbar.tsx
Labels: 🐛 fix, 🔥 remove

#258 ✨ feat: 판매자 페이지 상품 리스트 > 상세 navigate 추가
  src/domains/seller/areas/product/features/list/pages/ProductList.tsx
Labels: ✨ feat

#264 ✨ feat: 주문 데이터 관리 로직 개선 및 페이지네이션 추가
  src/domains/seller/areas/product/features/list/pages/ProductList.tsx
  src/domains/seller/areas/product/features/order/pages/ProductOrder.tsx
Labels: ✨ feat, 🎨 design

#267 🐛 fix: 페이지네이션 및 상태별 필터링 API 연동 수정
  src/domains/seller/areas/main/pages/SellerMain.tsx
  src/domains/seller/areas/product/features/order/pages/ProductOrder.tsx
Labels: ♻️ refactor, 🐛 fix

#268 🐛 fix: 오류 체크 로직 오류 수정
  src/domains/seller/areas/product/features/order/pages/ProductOrder.tsx
Labels: 🐛 fix

#269 🔥 remove: console.log 제거
  src/domains/main/areas/home/features/class-order/pages/MainClassOrderResultPage.tsx
  src/domains/main/areas/home/features/products/pages/ProductsOrderSuccess.tsx
  src/domains/seller/areas/class/features/insert/pages/ClassInsert.tsx
  src/domains/seller/areas/product/features/edit/pages/ProductEdit.tsx
  src/domains/seller/areas/resume/pages/ResumeVerification.tsx
  src/domains/seller/areas/store/features/chat/pages/StoreChat.tsx
  src/shared/areas/layout/features/header/Header.tsx
  src/shared/areas/navigation/features/navbar/store/Storenavbar.tsx
Labels: 🔥 remove

#289 🐛 fix: 스토어 개설 오류 alert 수정
  src/domains/main/areas/home/features/stores/pages/MainStoreOpenform.tsx
Labels: 🐛 fix

#292 🐛 fix: 판매자 메인 클래스 예약 통계 고정값 수정
  src/domains/seller/areas/main/pages/SellerMain.tsx
  src/domains/seller/areas/settlement/features/class/pages/SellerSettlementClass.tsx
  src/domains/seller/areas/settlement/features/main/pages/SellerSettlementMain.tsx
  src/domains/seller/areas/settlement/features/product/pages/SellerSettlementProduct.tsx
  src/shared/components/analytics/ClassStatsCard.tsx
Labels: 🐛 fix

#294 🎨 design: 상품/클래스 수정 AI 로딩바 추가
  src/domains/seller/areas/class/features/edit/pages/ClassEdit.tsx
  src/domains/seller/areas/class/features/insert/pages/ClassInsert.tsx
  src/domains/seller/areas/class/features/reservation/pages/ClassReservation.tsx
  src/domains/seller/areas/product/features/edit/pages/ProductEdit.tsx
  src/domains/seller/areas/product/features/insert/pages/ProductInsert.tsx
Labels: 🎨 design, 🐛 fix

#301 🐛 fix: 마이페이지 오류 수정
  src/domains/main/areas/mypage/pages/MainMypagePage.tsx
Labels: 🐛 fix, 📝 docs

#312 ✨ feat: 상품 상세 페이지 리뷰 작성 API 연결
  src/domains/main/areas/home/features/products/pages/MainProductsDetail.tsx
Labels: ✨ feat

#314 🐛 fix: 상품상세 페이지 접근시 조회수 증가 api 연결
  src/domains/main/areas/home/features/products/pages/MainProductsDetail.tsx
Labels: 🐛 fix

#319 🐛 fix: 마이페이지 및 장바구니 수정
  src/domains/main/areas/home/features/products/pages/MainProductsorder.tsx
  src/domains/main/areas/mypage/pages/MainMypageCart.tsx
  src/domains/main/areas/mypage/pages/MainMypageOrders.tsx
Labels: ✨ feat, 🎨 design, 🐛 fix

#320 🐛 fix: 주문상세 페이지 상태 수정
  src/domains/main/areas/mypage/pages/MainMypageOrderdetail.tsx
Labels: 🐛 fix

#321 🐛 fix: 현재 스토어 장바구니 오류 수정
  src/domains/main/areas/mypage/pages/MainMypageCart.tsx
Labels: 🐛 fix
